
include:
  - board: akdk_nrf52840
    shield: unsplitball36
    snippet: studio-rpc-usb-uart
    artificial-name: unsplitball36
  - board: akdk_nrf52840
    shield: settings_reset
    artificial-name: settings_reset
